version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - ng build
artifacts:
  files:
    - '**/*'
  base-directory: 'dist'